//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTGSL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTGSL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Double Call.
        /// </summary>
        internal static string AllowDoubleCall {
            get {
                return ResourceManager.GetString("AllowDoubleCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Open Comport.
        /// </summary>
        internal static string AutoOpenComport {
            get {
                return ResourceManager.GetString("AutoOpenComport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate.
        /// </summary>
        internal static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        internal static string Bed {
            get {
                return ResourceManager.GetString("Bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bed(s).
        /// </summary>
        internal static string Bed_s {
            get {
                return ResourceManager.GetString("Bed_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed Height.
        /// </summary>
        internal static string BedHeight {
            get {
                return ResourceManager.GetString("BedHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed ID/ LocationID.
        /// </summary>
        internal static string BedID {
            get {
                return ResourceManager.GetString("BedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BedInfo/ Location Info.
        /// </summary>
        internal static string BedInfo {
            get {
                return ResourceManager.GetString("BedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed Name/ Loaction Name.
        /// </summary>
        internal static string BedName {
            get {
                return ResourceManager.GetString("BedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed Properties.
        /// </summary>
        internal static string BedProperties {
            get {
                return ResourceManager.GetString("BedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beds Per Row.
        /// </summary>
        internal static string BedsPerRow {
            get {
                return ResourceManager.GetString("BedsPerRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      &amp;Save.
        /// </summary>
        internal static string butSave {
            get {
                return ResourceManager.GetString("butSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call by Region.
        /// </summary>
        internal static string CallbyRegion {
            get {
                return ResourceManager.GetString("CallbyRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call by Shift.
        /// </summary>
        internal static string CallbyShift {
            get {
                return ResourceManager.GetString("CallbyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call by Time.
        /// </summary>
        internal static string CallbyTime {
            get {
                return ResourceManager.GetString("CallbyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Top N.
        /// </summary>
        internal static string CallTopN {
            get {
                return ResourceManager.GetString("CallTopN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Wait Over.
        /// </summary>
        internal static string CallWaitOver {
            get {
                return ResourceManager.GetString("CallWaitOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Call.
        /// </summary>
        internal static string ClearAllCall {
            get {
                return ResourceManager.GetString("ClearAllCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Event.
        /// </summary>
        internal static string ConfigEvent {
            get {
                return ResourceManager.GetString("ConfigEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Manager.
        /// </summary>
        internal static string ConfigManager {
            get {
                return ResourceManager.GetString("ConfigManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application to apply changes.
        /// </summary>
        internal static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curator.
        /// </summary>
        internal static string Curator {
            get {
                return ResourceManager.GetString("Curator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data bits.
        /// </summary>
        internal static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime From.
        /// </summary>
        internal static string DatetimeFrom {
            get {
                return ResourceManager.GetString("DatetimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime To.
        /// </summary>
        internal static string DatetimeTo {
            get {
                return ResourceManager.GetString("DatetimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Bed.
        /// </summary>
        internal static string DeleteBed {
            get {
                return ResourceManager.GetString("DeleteBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Department.
        /// </summary>
        internal static string DeleteDepartment {
            get {
                return ResourceManager.GetString("DeleteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Employee.
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Job.
        /// </summary>
        internal static string DeleteJob {
            get {
                return ResourceManager.GetString("DeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Location.
        /// </summary>
        internal static string DeleteLocation {
            get {
                return ResourceManager.GetString("DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Region.
        /// </summary>
        internal static string DeleteRegion {
            get {
                return ResourceManager.GetString("DeleteRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Room.
        /// </summary>
        internal static string DeleteRoom {
            get {
                return ResourceManager.GetString("DeleteRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteU {
            get {
                return ResourceManager.GetString("DeleteU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to department(s).
        /// </summary>
        internal static string Department_s_ {
            get {
                return ResourceManager.GetString("Department_s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID.
        /// </summary>
        internal static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Info.
        /// </summary>
        internal static string DepartmentInfo {
            get {
                return ResourceManager.GetString("DepartmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name.
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Properties.
        /// </summary>
        internal static string DepartmentProperties {
            get {
                return ResourceManager.GetString("DepartmentProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to.
        /// </summary>
        internal static string DoYouWantTo {
            get {
                return ResourceManager.GetString("DoYouWantTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp. ID.
        /// </summary>
        internal static string EmpID {
            get {
                return ResourceManager.GetString("EmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to employee(s).
        /// </summary>
        internal static string Employee_s_ {
            get {
                return ResourceManager.GetString("Employee_s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Info.
        /// </summary>
        internal static string EmployeeInfo {
            get {
                return ResourceManager.GetString("EmployeeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee name.
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Properties.
        /// </summary>
        internal static string EmployeeProperties {
            get {
                return ResourceManager.GetString("EmployeeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Manager.
        /// </summary>
        internal static string EmployeesManager {
            get {
                return ResourceManager.GetString("EmployeesManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End All Call.
        /// </summary>
        internal static string EndAllCall {
            get {
                return ResourceManager.GetString("EndAllCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportFailed.
        /// </summary>
        internal static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportSuccess.
        /// </summary>
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F0001 - Options.
        /// </summary>
        internal static string F0001 {
            get {
                return ResourceManager.GetString("F0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failure.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Bed.
        /// </summary>
        internal static string FindBed {
            get {
                return ResourceManager.GetString("FindBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string grpHeight {
            get {
                return ResourceManager.GetString("grpHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help_ {
            get {
                return ResourceManager.GetString("Help_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help1 {
            get {
                return ResourceManager.GetString("Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire date.
        /// </summary>
        internal static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        internal static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital ID.
        /// </summary>
        internal static string HospitalID {
            get {
                return ResourceManager.GetString("HospitalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Info.
        /// </summary>
        internal static string HospitalInfo {
            get {
                return ResourceManager.GetString("HospitalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Name.
        /// </summary>
        internal static string HospitalName {
            get {
                return ResourceManager.GetString("HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Properties.
        /// </summary>
        internal static string HospitalProperties {
            get {
                return ResourceManager.GetString("HospitalProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NurseCall.
        /// </summary>
        internal static string HTGSL {
            get {
                return ResourceManager.GetString("HTGSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of Bed.
        /// </summary>
        internal static string InfoOfBed {
            get {
                return ResourceManager.GetString("InfoOfBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of Department.
        /// </summary>
        internal static string InfoOfDepartment {
            get {
                return ResourceManager.GetString("InfoOfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of Employee.
        /// </summary>
        internal static string InfoOfEmployee {
            get {
                return ResourceManager.GetString("InfoOfEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of Job.
        /// </summary>
        internal static string InfoOfJob {
            get {
                return ResourceManager.GetString("InfoOfJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of Location.
        /// </summary>
        internal static string InfoOfLocation {
            get {
                return ResourceManager.GetString("InfoOfLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of Region.
        /// </summary>
        internal static string InfoOfRegion {
            get {
                return ResourceManager.GetString("InfoOfRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info of Room.
        /// </summary>
        internal static string InfoOfRoom {
            get {
                return ResourceManager.GetString("InfoOfRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is existed.
        /// </summary>
        internal static string IsExisted {
            get {
                return ResourceManager.GetString("IsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is existed in.
        /// </summary>
        internal static string IsExistedIn {
            get {
                return ResourceManager.GetString("IsExistedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not empty.
        /// </summary>
        internal static string IsNotEmpty {
            get {
                return ResourceManager.GetString("IsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not found.
        /// </summary>
        internal static string IsNotFound {
            get {
                return ResourceManager.GetString("IsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not selected.
        /// </summary>
        internal static string IsNotSelected {
            get {
                return ResourceManager.GetString("IsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is number.
        /// </summary>
        internal static string IsNumber {
            get {
                return ResourceManager.GetString("IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s).
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job(s).
        /// </summary>
        internal static string Job_s_ {
            get {
                return ResourceManager.GetString("Job_s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job ID.
        /// </summary>
        internal static string JobID {
            get {
                return ResourceManager.GetString("JobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Info.
        /// </summary>
        internal static string JobInfo {
            get {
                return ResourceManager.GetString("JobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job name.
        /// </summary>
        internal static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Properties.
        /// </summary>
        internal static string JobProperties {
            get {
                return ResourceManager.GetString("JobProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Departments.
        /// </summary>
        internal static string ListOfDepartments {
            get {
                return ResourceManager.GetString("ListOfDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Employees.
        /// </summary>
        internal static string ListOfEmployees {
            get {
                return ResourceManager.GetString("ListOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Jobs.
        /// </summary>
        internal static string ListOfJobs {
            get {
                return ResourceManager.GetString("ListOfJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location(s).
        /// </summary>
        internal static string Location_s {
            get {
                return ResourceManager.GetString("Location_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location ID.
        /// </summary>
        internal static string LocationID {
            get {
                return ResourceManager.GetString("LocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Info.
        /// </summary>
        internal static string LocationInfo {
            get {
                return ResourceManager.GetString("LocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        internal static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Properties.
        /// </summary>
        internal static string LocationProperties {
            get {
                return ResourceManager.GetString("LocationProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location type.
        /// </summary>
        internal static string LocationType {
            get {
                return ResourceManager.GetString("LocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Lists.
        /// </summary>
        internal static string MailLists {
            get {
                return ResourceManager.GetString("MailLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Schedule.
        /// </summary>
        internal static string MailSchedule {
            get {
                return ResourceManager.GetString("MailSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Setup.
        /// </summary>
        internal static string MailSetup {
            get {
                return ResourceManager.GetString("MailSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        internal static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Bed.
        /// </summary>
        internal static string ModifyBed {
            get {
                return ResourceManager.GetString("ModifyBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Department.
        /// </summary>
        internal static string ModifyDepartment {
            get {
                return ResourceManager.GetString("ModifyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Employee.
        /// </summary>
        internal static string ModifyEmployee {
            get {
                return ResourceManager.GetString("ModifyEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Job.
        /// </summary>
        internal static string ModifyJob {
            get {
                return ResourceManager.GetString("ModifyJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Location.
        /// </summary>
        internal static string ModifyLocation {
            get {
                return ResourceManager.GetString("ModifyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Region.
        /// </summary>
        internal static string ModifyRegion {
            get {
                return ResourceManager.GetString("ModifyRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Room.
        /// </summary>
        internal static string ModifyRoom {
            get {
                return ResourceManager.GetString("ModifyRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bed.
        /// </summary>
        internal static string NewBed {
            get {
                return ResourceManager.GetString("NewBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Department.
        /// </summary>
        internal static string NewDepartment {
            get {
                return ResourceManager.GetString("NewDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee.
        /// </summary>
        internal static string NewEmployee {
            get {
                return ResourceManager.GetString("NewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        internal static string NewJob {
            get {
                return ResourceManager.GetString("NewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Location.
        /// </summary>
        internal static string NewLocation {
            get {
                return ResourceManager.GetString("NewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Region.
        /// </summary>
        internal static string NewRegion {
            get {
                return ResourceManager.GetString("NewRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Room.
        /// </summary>
        internal static string NewRoom {
            get {
                return ResourceManager.GetString("NewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse Call System.
        /// </summary>
        internal static string NurseCallSystem {
            get {
                return ResourceManager.GetString("NurseCallSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        internal static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port name.
        /// </summary>
        internal static string PortName {
            get {
                return ResourceManager.GetString("PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Time.
        /// </summary>
        internal static string ProcessTime {
            get {
                return ResourceManager.GetString("ProcessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region(s).
        /// </summary>
        internal static string Region_s {
            get {
                return ResourceManager.GetString("Region_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Height.
        /// </summary>
        internal static string RegionHeight {
            get {
                return ResourceManager.GetString("RegionHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region ID.
        /// </summary>
        internal static string RegionID {
            get {
                return ResourceManager.GetString("RegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Info.
        /// </summary>
        internal static string RegionInfo {
            get {
                return ResourceManager.GetString("RegionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        internal static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Properties.
        /// </summary>
        internal static string RegionProperties {
            get {
                return ResourceManager.GetString("RegionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register listen event from bed.
        /// </summary>
        internal static string RegisterListenEventFromBed {
            get {
                return ResourceManager.GetString("RegisterListenEventFromBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Functions.
        /// </summary>
        internal static string Right_Function {
            get {
                return ResourceManager.GetString("Right_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        internal static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to room(s).
        /// </summary>
        internal static string Room_s {
            get {
                return ResourceManager.GetString("Room_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Height.
        /// </summary>
        internal static string RoomHeight {
            get {
                return ResourceManager.GetString("RoomHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room ID.
        /// </summary>
        internal static string RoomID {
            get {
                return ResourceManager.GetString("RoomID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Info.
        /// </summary>
        internal static string RoomInfo {
            get {
                return ResourceManager.GetString("RoomInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Name.
        /// </summary>
        internal static string RoomName {
            get {
                return ResourceManager.GetString("RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Properties.
        /// </summary>
        internal static string RoomProperties {
            get {
                return ResourceManager.GetString("RoomProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectAll.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port.
        /// </summary>
        internal static string SerialPort {
            get {
                return ResourceManager.GetString("SerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port Settings.
        /// </summary>
        internal static string SerialPortSettings {
            get {
                return ResourceManager.GetString("SerialPortSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service(s).
        /// </summary>
        internal static string Service_s {
            get {
                return ResourceManager.GetString("Service_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ID.
        /// </summary>
        internal static string ServiceID {
            get {
                return ResourceManager.GetString("ServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Connect.
        /// </summary>
        internal static string SetConnect {
            get {
                return ResourceManager.GetString("SetConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts.
        /// </summary>
        internal static string Shifts {
            get {
                return ResourceManager.GetString("Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Templates.
        /// </summary>
        internal static string SoundTemplates {
            get {
                return ResourceManager.GetString("SoundTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop_ {
            get {
                return ResourceManager.GetString("Stop_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop1 {
            get {
                return ResourceManager.GetString("Stop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop bits.
        /// </summary>
        internal static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Form.
        /// </summary>
        internal static string TestForm {
            get {
                return ResourceManager.GetString("TestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Read Sound.
        /// </summary>
        internal static string TimeReadSound {
            get {
                return ResourceManager.GetString("TimeReadSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Refresh Data (milisecond).
        /// </summary>
        internal static string TimeRefreshData {
            get {
                return ResourceManager.GetString("TimeRefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Send Data.
        /// </summary>
        internal static string TimeSendData {
            get {
                return ResourceManager.GetString("TimeSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of Beds.
        /// </summary>
        internal static string TotalOfBeds {
            get {
                return ResourceManager.GetString("TotalOfBeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of Locations.
        /// </summary>
        internal static string TotalOfLocations {
            get {
                return ResourceManager.GetString("TotalOfLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of Rooms.
        /// </summary>
        internal static string TotalOfRooms {
            get {
                return ResourceManager.GetString("TotalOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ID.
        /// </summary>
        internal static string TypeID {
            get {
                return ResourceManager.GetString("TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        internal static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSelect All.
        /// </summary>
        internal static string UnSelectAll {
            get {
                return ResourceManager.GetString("UnSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        internal static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Shifts.
        /// </summary>
        internal static string WorkShifts {
            get {
                return ResourceManager.GetString("WorkShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
